spring.application.name=ScholarTrack

spring.datasource.url=jdbc:mysql://localhost:3306/scholartrack?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Jovi@22062008

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080